### ISSUE TITLE
Errors running esy

### ISSUE THREAD

**Issue by shinzui** [zploskey/hello-esy-dune-bsb#1]
Esy can't install `@esy-ocaml/substs`.

I get the following error:

```
info esy 0.3.4
error: package @esy-ocaml/substs is missing, run 'esy install' to fix that
  processing package: hello-esy-dune-bsb@0.1.0
esy: exiting due to errors above
```

**Comment by zploskey** [comment]
So, this won't work yet since we need to build a bunch of features into dune to support it. This is currently just a test package that depends on [Dune's bucklescript branch](https://github.com/ocaml/dune/tree/bucklescript). You can follow along in the discussion in the [BuckleScript issue](https://github.com/ocaml/dune/issues/140). I'll go ahead and spell this out a bit more in the readme here so I don't give anyone else the wrong idea.

**Comment by zploskey** [comment]
Thanks for bringing the `substs` issue to my attention. Installing it seems to have resolved that problem, but there's still lots to do on Dune to make things work. I added some info and links for people to find out where things are at. I'll open a WIP PR for Dune soon and link to that as well.
